# Numpy Array Operations Assignment

Personal Details
- Name: Sahiti Somalraju
- Email: ssomalra@iu.edu

In [4]:
import numpy as np

### Question 1
Write a NumPy program to test whether none of the elements of the following array is 12.  [[10,1,3], [3,5,12], [7,13,5]]

In [5]:
A = np.array([[10,1,3],[3,5,12],[7,13,5]])
print('Array:\n', A)
print('None of the elements in array is 12:', np.all(A!=12))

Array:
 [[10  1  3]
 [ 3  5 12]
 [ 7 13  5]]
None of the elements in array is 12: False


### Question 2
Write a NumPy program to convert the following array to int type: 
[15.0, 13.0, 28.0, 17.0, 11.0]

In [15]:
A = np.array([15.0,13.0,28.0,17.0,11.0])
print('Array:\n', A)
int_A = A.astype(int)
print('Array of integers:\n', int_A)

Array:
 [15. 13. 28. 17. 11.]
Array of integers:
 [15 13 28 17 11]


### Question 3
Write a NumPy program to create a random 2d array 7x7 with 49 elements and compute the mean and standard deviation of the array elements.

In [14]:
arr = np.random.randint(1,50,size=(7,7))
print('Array:\n', arr)

#mean
print('Mean:', np.mean(arr))

#standard deviation
print('Standard deviation:', np.std(arr))

Array:
 [[39 44 29 48 47 48  3]
 [ 5 25 38 33 39 21 49]
 [23 30 24 27 34 33  3]
 [12 34 11 17 26 28 31]
 [ 3 43  2 25  8 21 17]
 [16  8 27 13 35 10 10]
 [34 33 49  1 30  4 43]]
Mean: 25.163265306122447
Standard deviation: 14.356036828435924


### Question 4
Write a NumPy program to calculate sum of the elements along each row and each column for the following array: [[0,1,3], [6,13,21], [7,13,22]]

In [3]:
A = np.array([[0,1,3],[6,13,21],[7,13,22]])
print('Array:\n', A)
#Sum of all elements in array
print('Sum:', np.sum(A))

#Sum of elements row-wise
print('Row sum:\n', np.sum(A, axis=1))

#Sum of elements column-wise
print('Column sum:\n', np.sum(A, axis=0))

Array:
 [[ 0  1  3]
 [ 6 13 21]
 [ 7 13 22]]
Sum: 86
Row sum:
 [ 4 40 42]
Column sum:
 [13 27 46]


### Question 5
Write a NumPy program to calculate the square of elements in the following 2D array: [[10,11,13], [7,8,9]]

In [18]:
A = np.array([[10,11,13],[7,8,9]])
print('Original Array:\n', A)
print('Squared Array:\n', A**2)

Original Array:
 [[10 11 13]
 [ 7  8  9]]
Squared Array:
 [[100 121 169]
 [ 49  64  81]]


### Question 6
Display the names of the months between 2018 and 2019

In [19]:
print('Months between 2018 and 2019:\n', np.arange('2018','2019', dtype='datetime64[M]'))


Months between 2018 and 2019:
 ['2018-01' '2018-02' '2018-03' '2018-04' '2018-05' '2018-06' '2018-07'
 '2018-08' '2018-09' '2018-10' '2018-11' '2018-12']


### Question 7
Print the days between 2020-08 and 2020-09

In [20]:
print('Days between 2020-08 and 2020-09:\n', np.arange('2020-08','2020-09',dtype='datetime64[D]'))

Days between 2020-08 and 2020-09:
 ['2020-08-01' '2020-08-02' '2020-08-03' '2020-08-04' '2020-08-05'
 '2020-08-06' '2020-08-07' '2020-08-08' '2020-08-09' '2020-08-10'
 '2020-08-11' '2020-08-12' '2020-08-13' '2020-08-14' '2020-08-15'
 '2020-08-16' '2020-08-17' '2020-08-18' '2020-08-19' '2020-08-20'
 '2020-08-21' '2020-08-22' '2020-08-23' '2020-08-24' '2020-08-25'
 '2020-08-26' '2020-08-27' '2020-08-28' '2020-08-29' '2020-08-30'
 '2020-08-31']


### Question 8
Write a Numpy program to load forestfires dataset in Numpy array and explore it by doing the following:

- Print the shape of the dataset
- Check the shape of the dataset, excluding the last column
- Check the shape of the last column in the dataset
- Print the column names (features) up to the last column
- Print the last column name
- Check the type of all columns in the dataset. excluding the last column
- Check the type of the last column in the dataset
- Print the value of the 4th column for the 90th sample/data point in the dataset
- Print the value of the 7th column for the 300th sample/data point in the dataset

In [36]:
forestfire = np.genfromtxt('/Users/sahitisomalraju/Downloads/forestfires.csv', delimiter=',', 
                           dtype=None, encoding='utf-8')
print('Forestfires dataset:\n', forestfire)

Forestfires dataset:
 [['X' 'Y' 'month' ... 'wind' 'rain' 'area']
 ['7' '5' 'mar' ... '6.7' '0' '0']
 ['7' '4' 'oct' ... '0.9' '0' '0']
 ...
 ['7' '4' 'aug' ... '6.7' '0' '11.16']
 ['1' '4' 'aug' ... '4' '0' '0']
 ['6' '3' 'nov' ... '4.5' '0' '0']]


In [24]:
print('Shape of dataset:\n', forestfire.shape)

Shape of dataset:
 (518, 13)


In [26]:
print('Shape of dataset, excluding last column:\n', forestfire[:,:-1].shape)

Shape of dataset, excluding last column:
 (518, 12)


In [27]:
print('Shape of last column in dataset: \n', forestfire[:,-1:].shape)

Shape of last column in dataset: 
 (518, 1)


In [37]:
#Reuploaded the data as forestfire_col where parameter names=True so that we can extract the column names
forestfire_col = np.genfromtxt('/Users/sahitisomalraju/Downloads/forestfires.csv',
                               delimiter=',', names=True, encoding='utf-8')
print(forestfire)

[['X' 'Y' 'month' ... 'wind' 'rain' 'area']
 ['7' '5' 'mar' ... '6.7' '0' '0']
 ['7' '4' 'oct' ... '0.9' '0' '0']
 ...
 ['7' '4' 'aug' ... '6.7' '0' '11.16']
 ['1' '4' 'aug' ... '4' '0' '0']
 ['6' '3' 'nov' ... '4.5' '0' '0']]


In [39]:
print('Column names:\n', forestfire_col.dtype.names)

Column names:
 ('X', 'Y', 'month', 'day', 'FFMC', 'DMC', 'DC', 'ISI', 'temp', 'RH', 'wind', 'rain', 'area')


In [29]:
print('Last column name:\n', forestfire[0,-1])

Last column name:
 area


In [32]:
print('Type of the columns, except last column:\n', forestfire[0,:-1].dtype)

Type of the columns, except last column:
 <U7


In [31]:
print('Type of the last column:\n', forestfire[0,-1].dtype)

Type of the last column:
 <U4


In [33]:
print('Value of 4th column, 90th sample:\n', forestfire[90,3])

Value of 4th column, 90th sample:
 sat


In [35]:
print('Value of the 7th column, 300th sample:\n', forestfire[300,6])

Value of the 7th column, 300th sample:
 233.8
